### PR TITLE
Setup CSCS CI

### PR DESCRIPTION
**Pull request by kanduri**
Added config files and tweaking configurations in the backend

### CODE REVIEW

**Comment by kanduri** [comment]
cscs-ci run

**Comment by kanduri** [comment]
cscs-ci run

**Comment by frostedoyster** [comment]
Very weird @kanduri. It seems that compilation is failing because the compiler can't understand atomicAdd. Do you have any ideas?

**Comment by kanduri** [comment]
@frostedoyster 
I made some attempts to resolve the compilation errors. 
Regarding HPE, the polynomial order 0 (zero) implementation cannot work. We should remove it from the switch case ladder. In the file `hpe.cu`, we see multiple places where a divide-by-zero error can occur. For example:
```
int32_t i_monomial = threadIdx.x % polynomial_order;
```

**Review by frostedoyster — APPROVED** [review]
Thanks everyone!

**Pull request merged**
