### PR TITLE
Change column limit

### PR DESCRIPTION
**Pull request by frostedoyster**
Changes the column limit from 80 to 120 (#30)

### CODE REVIEW

**Comment by Luthaf** [comment]
I tweaked the formatting a bit, using a column length of 100, but allowing the code to go a couple of characters over with `PenaltyExcessCharacter`. While I was at it, I also cleaned up some code! Everything should be in a separate commit, and I can split it into a separate PR if you want.

CI seems unhappy, I'll fix it.

**Comment by Luthaf** [comment]
Looks like CI is hitting a bug in CMake: https://discourse.cmake.org/t/3-28-segmentation-fault-on-macos-11-runner/9588, which should be fixed in cmake 3.28.1

Do we want to wait a bit for this new release to be available, or should we change our configuration to use an older cmake?

**Comment by frostedoyster** [comment]
I would say let's use an older CMake

**Comment by Luthaf** [comment]
Should be good to go!

**Pull request merged**
